{"name": "test_phone_form_error[data2]", "status": "passed", "description": "账号或密码错误", "attachments": [{"name": "log", "source": "1c350345-962f-4d07-b9b9-2ac4761003ff-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'username': '16602159899', 'password': '111111', 'check': '用户名密码不匹配!'}"}], "start": 1581514561968, "stop": 1581514562694, "uuid": "3e087eea-61fa-4f95-ad2e-c5f309e8a7c9", "historyId": "058fce3e2ab67caed8ee7c316a3e02cc", "testCaseId": "7abdcb9e4c184004b48f7cf24249dd0d", "fullName": "TestCases.test_login_pytest.TestLogin#test_phone_form_error", "labels": [{"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-L7JJJ3C"}, {"name": "thread", "value": "14056-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login_pytest"}]}