{"name": "test_phone_form_error[data0]", "status": "passed", "description": "账号或密码错误", "attachments": [{"name": "log", "source": "744cf471-d6b0-4473-8ed9-48d498c0904a-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'username': '1660215989', 'password': 'Zyj888888', 'check': '用户不存在!'}"}], "start": 1581514560319, "stop": 1581514561246, "uuid": "efee15c5-1d30-45d5-80ee-701bad72cecb", "historyId": "294b9789e18469eabf65428012a35774", "testCaseId": "7abdcb9e4c184004b48f7cf24249dd0d", "fullName": "TestCases.test_login_pytest.TestLogin#test_phone_form_error", "labels": [{"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-L7JJJ3C"}, {"name": "thread", "value": "14056-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login_pytest"}]}