{"name": "test_login_failure[data2]", "status": "passed", "description": "登录失败", "attachments": [{"name": "log", "source": "b92555a5-473a-4779-89b0-edb375ff810f-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'username': '16602159899', 'password': '111111', 'check': '用户名密码不匹配!'}"}], "start": 1581902907590, "stop": 1581902908861, "uuid": "25208b1a-f259-4de3-ae7a-bd400605e1bf", "historyId": "2f22daba0194067109d223128c78670c", "testCaseId": "1b080540a6f1f5f538edbef9b820e3e6", "fullName": "TestCases.test_login.TestLogin#test_login_failure", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-L7JJJ3C"}, {"name": "thread", "value": "2480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}